### ISSUE TITLE
MKL not support M3 chip？

### ISSUE THREAD

**Issue by jamesguoxin** [Eydcao/BSMS-GNN#5]
I'm currently using a Macbook Pro shipped with M3 chip. While I try to conda (or pip) install MKL library that is required by sparse-dot-mkl library, it shows no package found error. I suspect it is because M3 chip is not supported by MKL pre-built binary. I want to confirm this issue and would like to ask is there any other alternatives to MKL library such like OpenBLAS?

**Comment by Eydcao** [comment]
Hi, I am afraid Mac could not afford training this project anyway...
Let me know if you encounter issues on Linux.
