### ISSUE TITLE
Transition between levels

### ISSUE THREAD

**Issue by sebestyenja** [Eydcao/BSMS-GNN#6]
Dear Yadi Cao,

I have a question about your model.

When the transition is happening between the different layers, does the node samples itself into the next layer or only the neighbouring nodes are aggregated? With other words, do self edges exist is the convolutional step between layers?

Thank you four your kind help!

**Comment by sebestyenja** [comment]
One more question. The BSMS-GNN use latent edge features only in the first, finest graph, then every other layer works as a graph convolution without any latent edge features, including the last, finest level in the up loop. Is that correct or I am mistaken? 
Thank you again!

**Comment by Eydcao** [comment]
1. Self edge exists or not is a design choice; it's just like adding a res connection or not before the node MLP
2. our edge feature will cat with the vector of itself, ie x_i - x_j, and its length. It includes the direction/offset between node pairs.
